### ISSUE TITLE
Make sure that we typecast both key and value

### ISSUE THREAD

**Issue by t-persson** [eiffel-community/eiffel-goer#17]
### Description

From the specification we can read (https://github.com/eiffel-community/eiffel-goer/blob/main/api/openapi-spec.yaml):
```
By default, all data types are treated as strings. It is possible to specify the data type by including it explicitly in the query:
          /events/?int(key1)>=value1&key2!=value2&double(key3)<value3
In this example, `key1` and `value1` are treated as integers, `key2` and `value2` are treated as strings and `key3` and `values3` are treated as doubles.
Currently only string (default), integer and double data types are supported.
```
But Goer currently only typecasts the `value`. It should not be a problem for now since we store all events in the MongoDB with the correct types, but we should fix this in the future.

### Motivation

We must follow the specification in order to be fully compatible.

**Comment by magnusbaeck** [comment]
@m-linner-ericsson and I agreed that other week that the type conversions will be dropped from the spec so I'm closing this issue.
