### ISSUE TITLE
Decision on how to add version to the README.md file

### ISSUE THREAD

**Issue by t-persson** [eiffel-community/eiffel-goer#7]
### Description

https://github.com/eiffel-community/eiffel-goer/blob/main/README.md#docker
The docker installation instructions today implicitly references the ":latest" tag
We need to make a decision on how we want to proceed with that specific installation instruction.
The options are:

1. Always push latest when we push a new tag.
2. Add an export VERSION=git describe command in the README.
3. Always update the README when doing new version tags.

Number 3 requires us to remember to update the README.

### Motivation

It should be clear how to install eiffel-goer.

### Exemplification

Easier to use = more people will use.

### Benefits

Clearer installation instructions

### Possible Drawbacks

None

**Comment by magnusbaeck** [comment]
@t-persson, now the README references the latest version but links to the GH Packages page with all versions. Perhaps that's enough to conclude this issue? If we start tagging the code those tags will show up as image tags as well (after adjusting the workflow slightly anyway).

**Comment by t-persson** [comment]
Yes. That should be enough
