### ISSUE TITLE
Implement the GET /search/{id} endpoint

### ISSUE THREAD

**Issue by t-persson** [eiffel-community/eiffel-goer#9]
### Description

In order for us to be compliant with the OpenAPI specification we must add the GET /search/{id} endpoint.
https://github.com/eiffel-community/eiffel-goer/blob/main/api/openapi-spec.yaml#L252

### Motivation

Compliance with the OpenAPI specification

### Exemplification

N/A

### Benefits

N/A

### Possible Drawbacks

None

**Comment by magnusbaeck** [comment]
Maybe we should close this issue as "not planned" rather than have it closed as "done" when the removal PR is merged? And remove it from the v1.0.0 milestone?

**Comment by t-persson** [comment]
I agree
